/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/dominion-worker/env.d.ts` (hash: 1beeb4bfb278b39690ef5ea0a0bfba04)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DOMINION_ROOMS: DurableObjectNamespace<import("./index").DominionRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "DominionRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
